data:
  esDatasetIndices:
    - ${ES_TRAINING_INDEX:ai_ktme_wheel_training}
#elasticsearch:
#  index: ${ES_INDEX:ai_ktme_data}
#  host: ${ES_HOST:192.168.0.170}
#  transportPort: 9200
#  readingType: _doc
spark:
  host: localhost
  port: 7077
  protocol: spark
server:
  port: ${PORT:8082}
  tomcat:
    max-swallow-size: 20000MB
storage:
  homeDir: ${AMVHC_HOME:D:\Sources\armored-vehicle\test-data\}
  dataDir: data
  modelDir: model
  modelIndexerDir: model_indexer
  csvDelimiter: ","
  dbHost: "192.168.3.19"
  dbPort: "3306"
  dbDatabase: "AMVHC"
  dbUser: "AMVHC_U"
  dbPassword: "!Tltmxpa0517"
algorithm:
  maxResult: 20
database:
  driverClass: org.mariadb.jdbc.Driver
  #  url: jdbc:mysql://${DB_HOST:221.148.11.152}:${DB_PORT:8012}/${DB_DATABASE:AMVHC}?useUnicode=yes&characterEncoding=UTF-8
  url: jdbc:mysql://${DB_HOST:192.168.3.19}:${DB_PORT:3306}/${DB_DATABASE:AMVHC}?useUnicode=yes&characterEncoding=UTF-8
  user: ${DB_USER:AMVHC_U}
  password: ${DB_PASSWORD:!Tltmxpa0517}
  properties:
    hibernate:
      hbm2ddl:
        auto: none
      connection:
        charSet: UTF-8
      dialect: org.hibernate.dialect.MariaDBDialect
#      show_sql: true
auth:
  secret: ${AUTH_SECRET_KEY:railroad}
  issuer: GAION
  expiresAfter: 1000 #hours
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB