data:
  esDatasetIndices:
    - ${ES_TRAINING_INDEX:ai_ktme_wheel_training}
elasticsearch:
  index: ${ES_INDEX:ai_ktme_data}
  host: ${ES_HOST:192.168.0.170}
  transportPort: 9200
  readingType: _doc
spark:
  host: localhost
  port: 7077
  protocol: spark
server:
  port: ${PORT:8083}
  tomcat:
    max-swallow-size: 20000MB
storage:
  homeDir: ${ETRI_RSS_HOME:\Sources\armored-vehicle\test-data}
  dataDir: data
  modelDir: model
  modelIndexerDir: model_indexer
  csvDelimiter: ","
algorithm:
  maxResult: 20
database:
  driverClass: org.mariadb.jdbc.Driver
  url: jdbc:mysql://${DB_HOST:192.168.0.52}:${DB_PORT:3306}/${DB_DATABASE:AMVHC}?useUnicode=yes&characterEncoding=UTF-8
  user: ${DB_USER:AMVHC_U}
  password: ${DB_PASSWORD:!Tltmxpa0517}
  properties:
    hibernate:
      hbm2ddl:
        auto: update
      connection:
        charSet: UTF-8
      dialect: org.hibernate.dialect.MariaDBDialect
      show_sql: true
auth:
  secret: ${AUTH_SECRET_KEY:railroad}
  issuer: GAION
  expiresAfter: 1000 #hours
